language: php
php:
  - 7.2
  - 7.1
env:
  - M2_VERSION=2.3.2
  - M2_VERSION=2.3.1
  - M2_VERSION=2.3.0
matrix:
  include:
    - php: 7.1
      env: M2_VERSION=2.2.9
    - php: 7.0
      env: M2_VERSION=2.2.9
cache:
  directories:
    - $HOME/.composer/cache
script:
  - dev/ci/build.sh
