language: php
php:
  - 7.0
  - 5.6
env:
  - M2_VERSION=2.1.5
  - M2_VERSION=2.1.3
  - M2_VERSION=2.1.2
  - M2_VERSION=2.1.1
  - M2_VERSION=2.1.0
  - M2_VERSION=2.0.13
matrix:
  include:
    - php: 5.5
      env: M2_VERSION=2.0.13
cache:
  directories:
    - $HOME/.composer/cache
script:
  - dev/ci/build.sh
